- hosts: smartlis_base_servers
  user: smartlis
  become: yes
  become_method: sudo
  tasks:
    
    - name: remove sources.list
      file:
        path: /etc/apt/sources.list
        state: absent
    
    - name: copy sources.list from github repo
      get_url:
        url: ftp://192.1.1.181/smartlis/sources.list
        dest: /etc/apt/
        
    - name: copy keys file
      get_url: 
        url: ftp://192.1.1.181/smartlis/trusted-keys
        dest: /home/
        
    - name: install keys
      apt_key:
        data: /home/trusted-keys
        state: present
        
    - name: update apt cache
      apt:
        update_cache: yes
