- hosts: 127.0.0.1
  user: root
  
  tasks:
  - name: Create slservers tower group
    tower_group:
      inventory: aviles
      name: smartlis_base_servers
      state: present
      tower_username: admin
      tower_password: "{{ tower_pass }}"
      
  - name: Add sl base servers to group
    shell: tower-cli host associate --host "{{ item }}" --group smartlis_base_servers
    with_items:
      - Smartlis_Repos
