- hosts: 127.0.0.1
  connection: local
  user: root
  
  tasks:
  - name: Delte test environment
    tower_group:
      inventory: aviles
      name: smartlis_base_servers
      state: absent
      tower_username: admin
      tower_password: "{{ tower_pass }}"
