- hosts: 127.0.0.1
  connection: local
  user: root
  
  tasks:
  - name: Power off sl base servers
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ item }}"
      state: poweredoff
      force: yes
    with_items:
      - sldatabase
      - slelasticbase
      - slstaticbase
      - slwwwbase
      - slbase1
      - slrabbitmqbase
      - slappbase
      
  - name: Remove sl base servers
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ item }}"
      state: absent
      force: yes
    with_items:
      - sldatabase
      - slelasticbase
      - slstaticbase
      - slwwwbase
      - slbase1
      - slrabbitmqbase
      - slappbase
      
  - name: Delete sl servers group
    tower_group:
      inventory: aviles
      name: smartlis_base_servers
      state: absent
      overwrite: no
      tower_username: admin
      tower_password: "{{ tower_pass }}"
      
  - name: Delete sl test servers
    tower_host:
      inventory: aviles
      name: "{{ item }}"
      state: absent
      tower_username: admin
      tower_password: "{{ tower_pass }}"
    with_items:
      - sldatabase
      - slelasticbase
      - slstaticbase
      - slwwwbase
      - slbase1
      - slrabbitmqbase
      - slappbase
      
