- hosts: "{{ servers }}"
  user: smartlis
  tasks:
  - name: Create VM from template
    vmware_guest:
      hostname: 10.232.7.105
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_name }}"
      template: "{{ template_name }}"
      folder: "{{ vm_folder }}"
      esxi_hostname: "{{ esxi_host }}"
      datacenter: " {{ datacenter }}"
      datastore: "{{ datastore_name }}"
      networks:
      - name: XLAN
        type: static
        ip: "{{ ip }}"
        netmask: 255.255.255.0
      wait_for_ip_address: yes
      customization:
        dns_servers:
        - 10.232.0.9
        - 10.233.4.40
