- hosts: "{{ servers }}"
  
  tasks:
  - name: 'Ensure that free space is greater than 10%'
    assert:
      that: 
        - item.size_available > item.size_total|float * 0.97
      msg: "failed disk space has reached 70% threshold"
    with_items: 
      - "{{ ansible_mounts }}"
    ignore_errors: yes
    register: disk_space

  - name: Send message when free space is less than 10%
    slack:
      token: T9N25BYMC/BEJ5TU0MP/UkjPmJsB7d1D0BAA2Belyjxf
      msg: "{{ ansible_hostname }} {{ item.item.mount }} < 10% free space"
    with_items: 
      - "{{ disk_space.results }}"
    when: item.failed == true
    delegate_to: localhost
