- hosts: "{{ servers }}"
  
  tasks:
  - name: 'Ensure that free space is greater than 30%'
    command: df -h {{ item.mount }}
    with_items: 
      - "{{ ansible_mounts }}"
    register: disk_space

  - name: Send message when free space is less than 30%
    debug:
      var: disk_space
