- hosts: "{{ servers }}"
  
  tasks:
  - name: Ensure that free space on {{ mountname }} is grater than 30%
    assert:
      that: 
        - not {{ item.mount == '{{mountname}}' and ( item.size_available < item.size_total - ( item.size_total|float * 0.7 ) ) }}
      msg: disk space has reached 70% threshold
    with_items: "{{ ansible_mounts }}"
