- hosts: "{{ servers }}"
  
  tasks:
  - name: 'Ensure that free space is greater than 30%'
    assert:
      that: 
        - item.mount != '/' or {{ item.mount == '/' and item.size_available > (item.size_total|float * 0.95) }}
      msg: "failed disk space has reached 70% threshold"
    with_items: 
      - "{{ ansible_mounts }}"
    ignore_errors: yes
    register: disk_space

  - name: Send message when free space is less than 30%
    slack:
      token: T9N25BYMC/BEJ5TU0MP/UkjPmJsB7d1D0BAA2Belyjxf
      msg: "{{ ansible_hostname }} {{ item.mount }} < 30% libre"
    with_items: 
      - "{{ ansible_mounts }}"
    when: disk_space.msg == "failed disk space has reached 70% threshold"
    delegate_to: localhost
