- hosts: 127.0.0.1
  connection: local
  become_user: root
  
  tasks:
  - name: Power on sl base servers
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ item }}"
      state: poweredon
      force: yes
    with_items:
      - sldatabase
      - slelasticbase
      - slstaticbase
      - slwwwbase
      - slbase1
      - slrabbitmqbase
      - slappbase
