- hosts: localhost

  tasks:
  - name: Change Network
    vmware_guest:
      hostname: '{{ vcenter_host }}'
      username: '{{ vcenter_user }}'
      password: '{{ vcenter_pass }}'
      datacenter: HUVM
      validate_certs: no
      name: "{{ item.name }}"
      state: present
      force: yes
      networks:
      - name: SL_Test
        ip: "{{ item.ip }}"
    loop:
      - { name: "SE00SARTL_BACKUP", ip: "192.1.1.100" }
